config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/new'

  root to: 'static_pages#home'

  resources :stocks

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates :symbol, presence: true,
                    length: { maximum: 5 }
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# before_action :authenticate_user!
before_action :configure_permitted_parameters, if:  :devise_controller?

protected
  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@stocks = Stock.all
  	StockQuote::Stock.new(api_key: 'pk_8899f76bbfb54c6389a6009749732b69')
  end

  def help
  end

  def about
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def new
    @stock = Stock.new
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def create
  	@stock = Stock.new(stock_params)
    @stock.user_id = current_user.id

  	@stock.save

  	redirect_to root_path
  end

  def update
    @stock = Stock.find(params[:id])

    if @stock.update(stock_params)
      redirect_to @stock
    else
      render 'edit'
    end
  end

  def show
  	@stock = Stock.find(params[:id])
  end

  def index
  	@stocks = Stock.all
  end

  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    redirect_to stocks_path
  end

  def what_action
    @ticker = StockQuote::Stock.quote(stock.symbol)
    @stock = Stock.find(params[:id])

    if ticker.latest_price < stock.stop_loss
      Below Stop Loss
    else
      Buy
    end
  end

private
  def stock_params
  	params.require(:stock).permit(:symbol, :target_entry, :target_entry_high, :stop_loss, :target_exit_1, :target_exit_2, :target_exit_3, :date, :timeframe, :source, :risk, :notes, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "TradeSleuths"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "Help",    help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar fixed-top navbar-light bg-light">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("logo.png", :size => "115x60", alt: "TradeSleuths"), root_path, id: "logo", :class => "navbar-brand" %>
      <% if user_signed_in? %>
        <%= link_to "New Watchlist Item", new_stock_path %>
      <% end %>
    </div>
  </div>
  <div>
    <% if user_signed_in? %>
      Welcome, <strong><%= current_user.first_name %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container">
      <%= yield %>
      <%#= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
<p>
  This is the About Us page for TradeSleuths
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  This is the help page for TradeSleuths
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
<body>  
  <h2>Welcome to TradeSleuths!</h2>

  <% if user_signed_in? %>
  	<%= link_to "New Watchlist Item", new_stock_path, class: "btn btn-large btn-primary" %>
  <% else %>
  	<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
  <% end %>
</div>

<div>
  <h2>Symbols we're watching:</h2>
 
<div class="container row">
    <% @stocks.each do |stock| %>
    <% ticker = StockQuote::Stock.quote(stock.symbol) %>
      <div class="card-deck col-lg-4 col-sm-6">
        <div class="card mb-3">
          <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" id="overview-tab" data-toggle="tab" href="#overview-<%= stock.id %>" role="tab" aria-controls="overview-<%= stock.id %>" aria-selected="true">Overview</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="targets-tab" data-toggle="tab" href="#targets-<%= stock.id %>" role="tab" aria-controls="targets-<%= stock.id %>" aria-selected="false">Targets</a>
              </li>
            </ul>
          </div>

          <div class="card-body">
            <h4 class="card-title"><%= link_to stock.symbol.upcase, stock_path(stock) %></h4>
            <h6 class="card-subtitle mb-2 text-muted"><%= number_to_currency(ticker.latest_price) %></h6>
            <% if ticker.change > 0 %>
              <h6 class="card-subtitle mb-2 text-success"><%= number_to_currency(ticker.change) %></h6>
            <% elsif ticker.change < 0 %>
              <h6 class="card-subtitle mb-2 text-danger"><%= number_to_currency(ticker.change) %></h6>
            <% else %>
              <h6 class="card-subtitle mb-2"><%= number_to_currency(ticker.change) %></h6>
            <% end %>
            <div class="tab-content mt-3" id="myTabContent">
              <div class="tab-pane show active" id="overview-<%= stock.id %>" role="tabpanel" aria-labelledby="overview-tab">
                <p class="card-text">
                  <% if ticker.latest_price < stock.stop_loss %>
                    Below Stop Loss
                  <% elsif ticker.latest_price > stock.target_entry && ticker.latest_price < stock.target_entry_high %>
                    In buy zone (<%= number_to_currency(stock.target_entry) %> - <%= number_to_currency(stock.target_entry_high) %>)
                  <% elsif ticker.latest_price > stock.target_exit_1 && ticker.latest_price < stock.target_exit_2 %>
                    Above first exit target
                  <% elsif ticker.latest_price > stock.target_exit_2 && ticker.latest_price < stock.target_exit_3 %>
                    Above second exit target
                  <% elsif ticker.latest_price > stock.target_exit_3 %>
                    Above third exit target
                  <% else %>
                    Wait
                  <% end %>
                </p>
              </div>
              
              <div class="tab-pane" id="targets-<%= stock.id %>" role="tabpanel" aria-labelledby="targets-tab">
                <p>Buy Zone: <%= number_to_currency(stock.target_entry) %> - <%= number_to_currency(stock.target_entry_high) %></p>
                <p>Stoploss: <%= number_to_currency(stock.stop_loss) %></p>
                <p>Exit Zone: <%= number_to_currency(stock.target_exit_1) %> - <%= number_to_currency(stock.target_exit_3) %></p>
              </div>
            </div>
          </div>
          <footer class="blockquote-footer"><%= stock.source %></footer>
        </div>
      </div>
    <% end %>
  </div>
</div>
</body>
</div>

app/views/stocks/_form.html.erb
<%= form_with model: @stock, local: true do |form| %>
 
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@stock.errors.count, "error") %> prohibited
        this stock from being saved:
      </h2>
      <ul>
        <% @stock.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :symbol %><br>
    <%= form.text_field :symbol %>
  </p>

  <p>
    <%= form.label :date %><br>
    <%= form.text_field :date %>
  </p>

  <p>
    <%= form.label :timeframe %><br>
    <%= form.text_field :timeframe %>
  </p>

 
  <p>
    <%= form.label :target_entry, "Target Entry Low" %><br>
    <%= form.text_field :target_entry %>
  </p>

  <p>
    <%= form.label :target_entry_high, "Target Entry High" %><br>
    <%= form.text_field :target_entry_high %>
  </p>  

  <p>
    <%= form.label :stop_loss %><br>
    <%= form.text_field :stop_loss %>
  </p>

  <p>
    <%= form.label :target_exit_1 %><br>
    <%= form.text_field :target_exit_1 %>
  </p>

  <p>
    <%= form.label :target_exit_2 %><br>
    <%= form.text_field :target_exit_2 %>
  </p>


  <p>
    <%= form.label :target_exit_3 %><br>
    <%= form.text_field :target_exit_3 %>
  </p>

  <p>
    <%= form.label :risk %><br>
    <%= form.text_field :risk %>
  </p>

  <p>
    <%= form.label :source %><br>
    <%= form.text_field :source %>
  </p>

  <p>
    <%= form.label :notes %><br>
    <%= form.text_area :notes %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/stocks/edit.html.erb
<h1>Edit stock</h1>
 
<%= form_with(model: @stock, local: true) do |form| %>
 
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@stock.errors.count, "error") %> prohibited
        this stock from being saved:
      </h2>
      <ul>
        <% @stock.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <%= render 'form' %>
 
<% end %>
 
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<div>
  <h2>Symbols we're watching:</h2>
 
<table class="table table-bordered table-sm">
  <tr>
    <tr>
      <th scope="col" rowspan="2">Symbol</th>
      <th scope="col">Low Entry</th>
      <th scope="col">Stop Loss</th>
      <th scope="col">Exit 1</th>
      <th scope="col">Exit 2</th>
      <th scope="col">Date</th>
      <th scope="col">Source</th>
      <%# <th scope="col" rowspan="2">Images</th> %>
      <th scope="col" rowspan="2">Notes</th>
      <th scope="col" colspan="2" rowspan="2">Actions</th>
    </tr>
    <tr>
      <th scope="col">High Entry</th>
      <th scope="col">Current</th>
      <th scope="col">Change</th>
      <th scope="col">Exit 3</th>
      <th scope="col">Timeframe</th>
      <th scope="col">Risk</th>
    </tr>
  </tr>
 
  <% @stocks.each do |stock| %>
    <% ticker = StockQuote::Stock.quote(stock.symbol) %>
    <tr>
      <tr>
        <td rowspan="2"><%= link_to stock.symbol.upcase, stock_path(stock) %></td>
        <td><%= number_to_currency(stock.target_entry) %></td>
        <td><%= number_to_currency(stock.stop_loss) %></td>
        <td><%= number_to_currency(stock.target_exit_1) %></td>
        <td><%= number_to_currency(stock.target_exit_2) %></td>
        <td><%= stock.date %></td>
        <td><%= stock.source %></td>
        <%# <td rowspan="2">TODO</td> %>
        <td rowspan="2"><%= stock.notes %></td>
        <td colspan="2" rowspan="2">
          <% if ticker.latest_price < stock.stop_loss %>
            Below Stop Loss
          <% elsif ticker.latest_price > stock.target_entry && ticker.latest_price < stock.target_entry_high %>
            In buy zone
          <% elsif ticker.latest_price > stock.target_exit_1 && ticker.latest_price < stock.target_exit_2 %>
            Above first exit target
          <% elsif ticker.latest_price > stock.target_exit_2 && ticker.latest_price < stock.target_exit_3 %>
            Above second exit target
          <% elsif ticker.latest_price > stock.target_exit_3 %>
            Above third exit target
          <% else %>
            Wait
          <% end %>
        </td>
      </tr>
      <tr>
        <td><%= number_to_currency(stock.target_entry_high) %></td>
        <td><%= number_to_currency(ticker.latest_price) %></td>
        <td><%= number_to_currency(ticker.change) %></td>
        <td><%= number_to_currency(stock.target_exit_3) %></td>
        <td><%= stock.timeframe %></td>
        <td><%= stock.risk %></td>
      </tr>
    </tr>
  <% end %>
</table>
</div>

app/views/stocks/new.html.erb
<h1> New Stock</h1>


<%= form_with scope: :stock, url: stocks_path, local: true do |form| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@stock.errors.count, "error") %> prohibited
        this item from being saved:
      </h2>
      <ul>
        <% @stock.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form' %>

  <%= link_to 'Back', stocks_path %>
<% end %>

app/views/stocks/show.html.erb
<h1>Stock!</h1>

<p>
  <strong>Symbol:</strong>
  <%= @stock.symbol %>
</p>
 
<p>
  <strong>Target Entry:</strong>
  <%= @stock.target_entry %>
</p>

<p>
  <strong>Stop Loss:</strong>
  <%= @stock.stop_loss %>
</p>

<p>
  <strong>Target Exit 1:</strong>
  <%= @stock.target_exit_1 %>
</p>

<p>
  <strong>Target Exit 2:</strong>
  <%= @stock.target_exit_2 %>
</p>

<p>
  <strong>Target Exit 3:</strong>
  <%= @stock.target_exit_3 %>
</p>

<p>
  <strong>Date:</strong>
  <%= @stock.date %>
</p>

<p>
  <strong>Timeframe:</strong>
  <%= @stock.timeframe %>
</p>

<p>
  <strong>Risk:</strong>
  <%= @stock.risk %>
</p>

<p>
  <strong>Source:</strong>
  <%= @stock.source %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @stock.notes %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %>
<%= link_to 'Destroy', stock_path(@stock),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', stocks_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<p>Find me in app/views/users/new.html.erb</p>